// Generated by CoffeeScript 1.11.1
var Event, Loader, Promise, Retry, Type, emptyFunction, getProto, isType, type;

emptyFunction = require("emptyFunction");

getProto = require("getProto");

Promise = require("Promise");

isType = require("isType");

Event = require("Event");

Retry = require("Retry");

Type = require("Type");

type = Type("Loader");

type.inherits(Function);

type.initArgs(function(args) {
  if (isType(args[0], Function)) {
    args[0] = {
      load: args[0]
    };
  }
});

type.defineOptions({
  load: Function,
  retry: Retry.Kind
});

type.createInstance(function() {
  var self;
  return self = function() {
    return self.load.apply(self, arguments);
  };
});

type.defineValues({
  retry: function(options) {
    return options.retry;
  },
  __load: function(options) {
    if (getProto(this).__load !== Loader.prototype.__load) {
      return;
    }
    return options.load;
  }
});

type.defineReactiveValues({
  _loading: null
});

type.addMixin(Event.Mixin, {
  didAbort: null,
  didFail: {
    error: Error.Kind
  }
});

type.defineGetters({
  isLoading: function() {
    return this._loading !== null;
  }
});

type.defineMethods({
  load: function() {
    var aborted, args, onAbort, ref;
    if (this.isLoading) {
      return this._loading;
    }
    if ((ref = this._retry) != null ? ref.isRetrying : void 0) {
      this._retry.reset();
    }
    aborted = false;
    onAbort = this.once("didAbort", function() {
      return aborted = true;
    });
    onAbort.start();
    args = arguments;
    return this._loading = Promise["try"]((function(_this) {
      return function() {
        return _this.__load.apply(_this, args);
      };
    })(this)).always((function(_this) {
      return function() {
        onAbort.detach();
        return _this._loading = null;
      };
    })(this)).then((function(_this) {
      return function(result) {
        if (aborted) {
          return;
        }
        return _this.__onLoad(result);
      };
    })(this)).fail((function(_this) {
      return function(error) {
        _this.emit("didFail", error);
        if (typeof _this._retry === "function") {
          _this._retry(function() {
            return _this.load();
          });
        }
        throw error;
      };
    })(this));
  },
  abort: function() {
    this._retry && this._retry.reset();
    if (!this.isLoading) {
      return;
    }
    this.emit("didAbort");
    this._loading = null;
  },
  unload: function() {
    this.abort();
    this.__onUnload();
  }
});

type.defineHooks({
  __load: null,
  __onLoad: emptyFunction.thatReturnsArgument,
  __onUnload: emptyFunction
});

module.exports = Loader = type.build();
